// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXM5HBoSPYUnow7_97XBWQ9sta4V5Yl6c',
    appId: '1:161603574509:web:84d122ff674e971e5d0ae4',
    messagingSenderId: '161603574509',
    projectId: 'fruits-hub-c2567',
    authDomain: 'fruits-hub-c2567.firebaseapp.com',
    storageBucket: 'fruits-hub-c2567.firebasestorage.app',
    measurementId: 'G-XDHZ620JQ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxgWc4UbRmzO5J9x8lvTjcctc1fuv_qzk',
    appId: '1:161603574509:android:51f65d0bdbf0a39d5d0ae4',
    messagingSenderId: '161603574509',
    projectId: 'fruits-hub-c2567',
    storageBucket: 'fruits-hub-c2567.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpASnsBWbHTldZFdbzrd6MVDq5dKAhK4Y',
    appId: '1:161603574509:ios:bc259c93b67ba9895d0ae4',
    messagingSenderId: '161603574509',
    projectId: 'fruits-hub-c2567',
    storageBucket: 'fruits-hub-c2567.firebasestorage.app',
    androidClientId: '161603574509-8sg29dck3d4uksr7i9ldfhukrjj78k1i.apps.googleusercontent.com',
    iosClientId: '161603574509-6858ki22egp4qoue88vfbnh4e2d9sehf.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsHubDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpASnsBWbHTldZFdbzrd6MVDq5dKAhK4Y',
    appId: '1:161603574509:ios:bc259c93b67ba9895d0ae4',
    messagingSenderId: '161603574509',
    projectId: 'fruits-hub-c2567',
    storageBucket: 'fruits-hub-c2567.firebasestorage.app',
    androidClientId: '161603574509-8sg29dck3d4uksr7i9ldfhukrjj78k1i.apps.googleusercontent.com',
    iosClientId: '161603574509-6858ki22egp4qoue88vfbnh4e2d9sehf.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsHubDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXM5HBoSPYUnow7_97XBWQ9sta4V5Yl6c',
    appId: '1:161603574509:web:33e8f71db5e3f9a25d0ae4',
    messagingSenderId: '161603574509',
    projectId: 'fruits-hub-c2567',
    authDomain: 'fruits-hub-c2567.firebaseapp.com',
    storageBucket: 'fruits-hub-c2567.firebasestorage.app',
    measurementId: 'G-Q3MN4LXY1H',
  );
}
